### ISSUE TITLE
the talkingdata demo produces negative results

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1797]
![image](https://user-images.githubusercontent.com/3725932/167787196-a155a628-95ea-45d4-a585-64339d6fd429.png)

The trained model file model.json attached as well
[model.txt](https://github.com/4paradigm/OpenMLDB/files/8667429/model.txt)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs (0.5.x)](https://trello.com/c/WhbjlRN2/69-bugs-05x)

**Comment by aceforeverd** [comment]
occur occasionally. we may rewrite those code later

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by lumianph** [comment]
we also should add the doc, this issue will be assigned to @xuduling

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [the talking data demo](https://trello.com/c/xSeVkLLX/101-the-talking-data-demo)

**Comment by vagetablechicken** [comment]
I'll use sklearn style `XGBClassifier` to rewrite the training part, so that the result will be like 
![image](https://user-images.githubusercontent.com/24697960/173771632-bcbb0c20-39f4-42d4-96c4-dfd9f470a08c.png)

returns 0/1, not float

And the sample data `train_sample.csv` has no label 1, label 0 rows are so many, so I'll make a new sample(random select) and contains some label 1 rows.
