### ISSUE TITLE
Auto release the installing package of macos 

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1894]
add the workflow to release the installing package of macos  automatically when a new tag created

**Comment by aceforeverd** [comment]
dup #258

**Comment by aceforeverd** [comment]
somebody can take this if u are interested in workflow

**Comment by mangoGoForward** [comment]
Hi, I want to confirm that whether this issue is resolved.
MacOS build like this:
https://github.com/4paradigm/OpenMLDB/blob/282ce34a54e71e9fdda5d593a7bc67dba6af9f94/.github/workflows/hybridse-ci.yml#L53
Release package like this:
https://github.com/4paradigm/OpenMLDB/blob/282ce34a54e71e9fdda5d593a7bc67dba6af9f94/.github/workflows/cicd.yaml#L155-L162

**Comment by aceforeverd** [comment]
> Hi, I want to confirm that whether this issue is resolved. MacOS build like this:
> 
> https://github.com/4paradigm/OpenMLDB/blob/282ce34a54e71e9fdda5d593a7bc67dba6af9f94/.github/workflows/hybridse-ci.yml#L53
> 
> 
> Release package like this:
> https://github.com/4paradigm/OpenMLDB/blob/282ce34a54e71e9fdda5d593a7bc67dba6af9f94/.github/workflows/cicd.yaml#L155-L162

Unresolved. we need add a job in `cicd.yaml` runs on macos, that compile and release artifacts of macos. The `macos-build` job in hybridse-ci is not relevant
