### ISSUE TITLE
Support performance_sensitive config in jdbc java sdk

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#605]
We should support setting `performance_sensitive` for java sdk.

**Comment by tobegit3hub** [comment]
We may add the config `performance_sensitive`  in `SdkOption`.

```
public class SdkOption {
    private String zkCluster;
    private String zkPath;
    private long sessionTimeout = 10000;
    private Boolean enableDebug = false;
    private long requestTimeout = 60000;
    // TODO: add bool performance_sensitive
```

**Comment by zekai427** [comment]
> We may add the config `performance_sensitive` in `SdkOption`.
> 
> ```
> public class SdkOption {
>     private String zkCluster;
>     private String zkPath;
>     private long sessionTimeout = 10000;
>     private Boolean enableDebug = false;
>     private long requestTimeout = 60000;
>     // TODO: add bool performance_sensitive
> ```

Another solution is adopted. Now, we can set performance_sensitive by using executeSQL("set performance_sensitive = true") in JDBC java sdk.

**Comment by tobegit3hub** [comment]
Users can set by executing SQL `set performance_sensitive=false` instead of passing parameters in config.

**Comment by jingchen2222** [comment]
> Users can set by executing SQL `set performance_sensitive=false` instead of passing parameters in config.

I recommend JDBC users setting performance_sensitive by configuring connection options or invoke `SetPerformanceSensitive() `instead of executeSQL("set xxxxx=xxx").  Because:
- We can't find an appropriate way to perform setting `performance_sensitive` during `executeSQL`
- This isn't the general way to deal with system or session variables. Generally, users set system/session variables via connection. e.g. `jdbc:mysql://localhost:3306/test?sql_mode='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY'&serverTimezone=UTC&useLegacyDatetimeCode=false`

**Comment by jingchen2222** [comment]
> 
> Another solution is adopted. Now, we can set performance_sensitive by using executeSQL("set performance_sensitive = true") in JDBC java SDK.

How does it work?
Now the `executeSQL` only responsible for executing queries. SQL like `SET xxx = xxx` won't be accepted.

**Comment by Kanekanekane** [comment]
> > Another solution is adopted. Now, we can set performance_sensitive by using executeSQL("set performance_sensitive = true") in JDBC java SDK.
> 
> How does it work? Now the `executeSQL` only responsible for executing queries. SQL like `SET xxx = xxx` won't be accepted.

Can we consider adding SetPerformanceSensitive in JDBC, like: 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/26684958/141050125-b832a0da-5254-46bf-8bc1-bfa2b9416084.png">, and then we can set performance sensitive in JDBC.
I think this kind of realization is better than add performance sensitive in router_options, because we probably set it frequently, but router option is more like a constant setting.

**Comment by zekai427** [comment]
> > Another solution is adopted. Now, we can set performance_sensitive by using executeSQL("set performance_sensitive = true") in JDBC java SDK.
> 
> How does it work? Now the `executeSQL` only responsible for executing queries. SQL like `SET xxx = xxx` won't be accepted.

We will support execute("set performance_sensitive = true") in this issue.
Linked: https://github.com/4paradigm/OpenMLDB/issues/666

**Comment by zekai427** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JDBC APIs standardisation](https://trello.com/c/BSUCBFig/14-jdbc-apis-standardisation)

**Comment by tobegit3hub** [comment]
Close since we will not expose the API to set `performance_sensitive` for users.
