### ISSUE TITLE
Support set execute_mode in CLI

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#714]
We may support setting `execute_mode` as `online` or `offline` in command-cli and SQL clients.

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CLI for offline jobs with unified metadata store](https://trello.com/c/rcSLPVcy/21-cli-for-offline-jobs-with-unified-metadata-store)

**Comment by tobegit3hub** [comment]
Depends on the conclusion of https://github.com/4paradigm/OpenMLDB/discussions/816 .

**Comment by jingchen2222** [comment]
> Depends on the conclusion of #816.

I think we haven't reached a conclusion. We will discuss it next week. 
In fact, we might not need 'set execute_mode=xxx' to decide on an executing mode. Since SQL queried can be executed "offline" by default in CLI. SQL deploying will be executed/compiled "online" automatically. 
I think the big problem is how to deal with online data loading and offline data loading without setting configuration. Let talk about that next week as well.

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Eliminate the concept of performance-sensitive mode for users](https://trello.com/c/kISPjYBa/31-eliminate-the-concept-of-performance-sensitive-mode-for-users)

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [data import for offline and online in the task manager](https://trello.com/c/OqReyYcD/23-data-import-for-offline-and-online-in-the-task-manager)

**Comment by vagetablechicken** [comment]
We only support it on sql_client, so the variable `execute_mode` won't store in sql cluster router.
We'll move it into router later.
