### ISSUE TITLE
Compare with mysql-sqlalchmey to check if throws exception for incorrect connection

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#962]
Check with `mysql-sqlalchemey` for incorrect connection.

**Comment by HuilinWu2** [comment]
Common step to establish the DBAPI connection:

`from sqlalchemy import create_engine`
`mysql+pymysql://<username>:<password>@<host>/<dbname>[?<options>]`
`mysql+pymysql:///root:whl88798@127.0.0.1:3307/db_huilin`
due to `create_engine` is a kind of lazy initialization, whatever we put into it, it still returns an `Engine` object

`connection = engine.connect()`
in this step, it throw exceptions for incorrect connection, e.g.:
`Can't connect to MySQL server`

**Comment by tobegit3hub** [comment]
We should throw exception for the incorrect connection just like what mysql did.

**Comment by HuilinWu2** [comment]
after testing, our connection shows exception as follows:
`Exception: init openmldb sdk erred`

**Comment by tobegit3hub** [comment]
Done.
